### ISSUE TITLE
Deploy to Production from PR

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/cloudflare-deploy-action#8]
I'm guessing this registered as a production deploy because the fork's branch name (development) matches our default branch name (development)

Our continuous deploys are designed to automatically consider everything a preview deploy unless it is merged to the default branch.  

Consider modifying the code to be actively aware that the event is coming from a pull request. If it is then we know to disable production deploys. Otherwise double check for a straight commit to default branch I suppose. 

> The crazy part here is that your pull deployed to production. I thought we fixed that a few weeks ago. Not sure if I messed up the settings on Cloudflare when I rolled back last night. Thanks for the fix. 

_Originally posted by @pavlovcik in https://github.com/ubiquity/pay.ubq.fi/pull/213#issuecomment-2026462349_

**Comment by EresDev** [comment]
I have reproduced the issue successfully. 

A pull request from fork's development branch deploys it as production because there are two arguments being passed to cloudflare during page deployment. 
- production branch
- current branch

Both happen to be `development` in the issue. Currently, it appears that these two arguments are of no other use for cloudflare than to know if the deployment is production or preview.   

I have two solutions and I am likely going to go with first one. 

1. Modify the `cloudflare-deploy-action`. If it a pull request, and branch name is development, modify the `current branch`  argument to cloudflare deployment as something like `development-from-pr`.  
2. The second solution is to deploy PRs to a separate cloudflare pages project with a domain like `pr-pay.ubq.fi.....`. It will require a second `cloudflare_project_name` in GitHub secretes and passing that along the entire chain of deployment.

**Comment by 0x4007** [comment]
It would suggest internally that it uses the same syntax as GitHub for example `ubiquity:development` to represent its our dev branch. 

I also added extra time here because it's really tedious to test so please be sure to set it up for testing on your end 

![image](https://github.com/ubiquity/cloudflare-deploy-action/assets/4975670/fad0da93-f957-4aa3-8b86-bd6d5d272a0d)

**Comment by EresDev** [comment]
> It would suggest internally that it uses the same syntax as GitHub for example ubiquity:development to represent its our dev branch.

I have modified the suggestion of `ubiquity:development` branch name to `ubiquity/development` because colon ":" has some other uses in git and it appears that colon is not allowed in branch name.
